"""feat: return traffic value for admin in db

Revision ID: 81f9d131964b
Revises: 20240602
Create Date: 2025-11-04 11:32:58.083791

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81f9d131964b"
down_revision: Union[str, None] = "20240602"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("admins", sa.Column("return_traffic", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "admins", "traffic", existing_type=sa.INTEGER(), nullable=False, default=0
    )

    # ### end Alembic commands ###
